<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:bas="http://baseone.nordlbit.de">
    <soapenv:Header>
        <bas:NlbInstitutsnummer>909</bas:NlbInstitutsnummer>
        <bas:ClientId>Postman</bas:ClientId>
    </soapenv:Header>
    <soapenv:Body>
        <bas:KontoAendernEingabePO>
            <bas:GeschaeftsArtTechn>110</bas:GeschaeftsArtTechn>
            <bas:KontoNr>1828760871</bas:KontoNr>
            <bas:Blz>700100</bas:Blz>
            <bas:Zusatztext>Der Text</bas:Zusatztext>
        </bas:KontoAendernEingabePO>
    </soapenv:Body>
</soapenv:Envelope>
