#Get Access Token
@accessToken = .......


# SOAP-Service
POST https://api.stage.example.com/soap-service
Content-Type: text/xml
Authorization: Bearer {{accessToken}}
SOAPAction: "http://your.namespace.com/YourAction"

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:your="http://your.namespace.com/">
    <soapenv:Header/>
    <soapenv:Body>
        <your:YourRequest>
            <your:Parameter1>Wert1</your:Parameter1>
            <your:Parameter2>Wert2</your:Parameter2>
        </your:YourRequest>
    </soapenv:Body>
</soapenv:Envelope>